# for github.com
X-Zalando-Team: "acid"
# type should be one of [code, doc, config, tools, secrets]
# code will be the default value, if X-Zalando-Type is not found in .zappr.yml
X-Zalando-Type: code

approvals:
  groups:
    zalando:
      minimum: 2
      from:
        orgs:
          - zalando