apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: operatorconfigurations.acid.zalan.do
spec:
  group: acid.zalan.do
  names:
    kind: OperatorConfiguration
    listKind: OperatorConfigurationList
    plural: operatorconfigurations
    shortNames:
    - pgc
    singular: operatorconfiguration
  scope: Namespaced
  version: v1
