apiVersion: v1
kind: Service
metadata:
  name: postgres-operator
spec:
  selector:
    app.kubernetes.io/instance: postgres-operator
    app.kubernetes.io/name: postgres-operator
  ports:
  - port: 80
    targetPort: 8080
