pipeline {
    
    agent {
        dockerfile {
            dir 'charts/postgres-operator'
            args '-u root:root --network="host"'
        }
    }

    stages {
        stage('Update Helm dependencies') {
            steps {
                sh "cd charts/postgres-operator; helm dependency update"
            }
        }

        stage('Run Helm lint') {
            steps {
                sh script: "cd charts/postgres-operator; helm lint --with-subcharts", returnStatus: true
            }
        }

        stage('Package Helm chart') {
            steps {
                sh "cd charts/postgres-operator; helm package ."
            }
        }

        stage('Push Helm chart') {
            when {
                branch "main"
            }
            steps {
                sh "cd charts/postgres-operator; curl --fail --data-binary \"@\$(ls postgres-operator-*.tgz)\" http://localhost:8081/api/charts"
            }
        }
    }

    post {
        always {
            sh "chmod -R 777 ."
            cleanWs ()
        }
    }
}
