apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgresql-operator-default-configuration.yaml
- operator-service-account-rbac.yaml
- postgres-operator.yaml
- api-service.yaml
