ARG base_image=alpine:3.15
FROM golang:1.18.3 as build
WORKDIR /workspace
ENV GO111MODULE=on \
    GOPROXY=https://goproxy.cn,direct \
    BINARY=postgres-operator
COPY . .
RUN CGO_ENABLED=0 go build -o build/linux/${BINARY} ./cmd/main.go

FROM ${base_image}
LABEL maintainer="Team ACID @ Zalando <team-acid@zalando.de>"
# We need root certificates to deal with teams api over https
RUN apk --no-cache add curl \
    apk --no-cache add ca-certificates

COPY --from=build /workspace/build/linux /

RUN addgroup -g 1000 pgo
RUN adduser -D -u 1000 -G pgo -g 'Postgres Operator' pgo

USER 1000:1000

ENTRYPOINT ["/postgres-operator"]
