def VERSION_TO_DEPLOY = '1.6.1'

pipeline {

    
    agent {
        dockerfile {
            dir 'charts'
            args '-u root:root --network="host"'
        }
    }

    stages {
        stage('Update Helm dependencies') {
            steps {
                sh "cd charts/postgres-operator; helm dependency update"
                sh "cd charts/postgres-operator-ui; helm dependency update"
            }
        }

        stage('Run Helm lint') {
            steps {
                sh script: "cd charts/postgres-operator; helm lint --with-subcharts", returnStatus: true
                sh script: "cd charts/postgres-operator-ui; helm lint --with-subcharts", returnStatus: true
            }
        }

        stage('Package Helm charts') {
            steps {
                sh "cd charts/postgres-operator; helm package ."
                sh "cd charts/postgres-operator-ui; helm package ."
            }
        }

        stage('Push Helm charts') {
            when {
                branch "master"
            }
            steps {
                sh "cd charts/postgres-operator; curl --data-binary \"@postgres-operator-${VERSION_TO_DEPLOY}.tgz\" http://localhost:8081/api/charts"
                sh "cd charts/postgres-operator-ui; curl --data-binary \"@postgres-operator-ui-${VERSION_TO_DEPLOY}.tgz\" http://localhost:8081/api/charts"
            }
        }
    }

    post {
        always {
            sh "chmod -R 777 ."
            cleanWs ()
        }
    }
}
